### ISSUE TITLE
Downloading formats getting mixed up and not rightly stated

### ISSUE THREAD

**Issue by SI0209** [Dniel97/orpheusdl-tidal#15]
I was trying to download a Dolby Atmos track and it got downloaded as a FLAC file, I tried downloading a FLAC file and it got downloaded as an .m4a file. And when I was trying to download an MQA track, even though it did say 24bit 96khz on the cmd while downloading. On the file properties, it showed it as 24bit 48khz. And all the right settings are set to true.

**Comment by yarrm80s** [comment]
@SI0209 What tracks are you downloading that are giving incorrect codecs? What's your Tidal subscription tier?

**Comment by Dniel97** [comment]
> And when I was trying to download an MQA track, even though it did say 24bit 96khz on the cmd while downloading. On the file properties, it showed it as 24bit 48khz. And all the right settings are set to true.

My module reads the MQA bitstream metadata from the FLAC file, so that means in order to get 96kHz 24bit you need a MQA capable DAC/Software which supports "unfolding". MQA Software uses the "Core Decoder" such as Tidal, UAPP, Roon or Audirvana can only do the first unfold up to 96kHz 24 bit. For anything higher you need a MQA DAC which a "MQA Renderer" or "MQA Full Decoder" which can decode up to 384kHz 24 bit. The shown MQA sample rate is always a multiple of the actual file sample rate, f.e. if the FLAC file is 44.1kHz 24 bit the MQA sample rate can either be 88.2, 176.4 or 352,8 Khz and if the FLAC file has a sample rate of 48kHz the MQA sample rate can either be 96, 192, 384kHz.

Check out [Bob Talks](https://bobtalks.co.uk/blog/science-mqa/mqa-playback) for more information.
