### ISSUE TITLE
explanation about the other config options

### ISSUE THREAD

**Issue by ViPiMP** [Dniel97/orpheusdl-tidal#3]
Tried to configure the "covers" and "advanced" subcategory in the settings.json file. 
The problem is that I don't have any template or explanation, what makes it just a way too big guess and try game. Maybe you could add some informations about the possible config options in the README file, if modifying these settings is possible. 

Greetings,
ViPiMP

**Comment by anjoku** [comment]
Hi,

What do you want to achieve?
I left the settings in "Covers" and "Advanced" as they are and it fits me perfect for me.
I just adapted "formatting".

greeting
Andre

**Comment by yarrm80s** [comment]
Leave the advanced section alone. For covers, essentially there are two sets of settings, one for the covers that go into the track file as a tag, and one set for external covers. You can set what resolution you want the covers for each to be, and you can choose the compression level (high compression = lower quality with jpg and webp, doesn't change anything with png since that's lossless). You're right, it should be added to the readme or to the wiki or something

**Comment by Dniel97** [comment]
Thanks to @yarrm80s for answering the options, totally forgot those.
