### ISSUE TITLE
Hifi or Lossless?

### ISSUE THREAD

**Issue by okay-bullo** [Dniel97/orpheusdl-tidal#31]
which is better hifi or lossless?

**Comment by yarrm80s** [comment]
@okay-bullo technically on Master tracks you get MQA either way so HiFi, but don't download the Master versions of tracks anyways because MQA is garbage

**Comment by okay-bullo** [comment]
@yarrm80s wait how is MQA garbage? I thought it was higher quality than flac

**Comment by okay-bullo** [comment]
@yarrm80s wait wait wait wait. Does that mean MQA is worse than flac (quality wise)? If so i need to redownload everything.

**Comment by Dniel97** [comment]
So if you have a MQA DAC you could argue it's useful for you but as soon as you don't have one there is no real benefit because the largest MQA files on TIDAL are 48 kHz/24 bit, which denn gets decoded (with an MQA DAC) to 96kHz/192kHz. If the MQA file is 44.1/16 (it's arguably worse than CD quality) it gets decoded to 88.2/176.4/352.8 kHz and well because it's 16 bit, you only get a 13 bit file if played with a non MQA Decoder. So because the discussion has nothing to do with the module, I'm going to close this issue.

PS. Even room has 3 options for MQA:

![IMG_20230523_072915_163](https://github.com/Dniel97/orpheusdl-tidal/assets/6324072/8da51c81-c46d-41aa-8848-301785aa6495)
