### ISSUE TITLE
spatial_codecs setting has no effect

### ISSUE THREAD

**Issue by NotSimone** [Dniel97/orpheusdl-tidal#67]
**Describe the bug**
The `spatial_codecs` setting appears to not do anything. Setting `enable_mobile` to true or false also has a side effect of enabling/disabling Dolby Atmos downloads.

**To Reproduce**
```
    "global": {
        "codecs": {
            "proprietary_codecs": false,
            ....
        },
    },
    "modules": {
        "tidal": {
            ....
            "enable_mobile": false,
            ....
        }
    }
```

**Expected behavior**
If a track has a Dolby Atmos format available, then having `spatial_codecs` set to true should download this file, and should download another available format if set to false. The `enable_mobile` setting should not be affecting this behaviour.

I suspect its just a side effect of Tidal streaming surround sound to TVs and not to mobiles so perhaps there's not much to do here apart from explicitly documenting this behaviour.

**Comment by OrfiDev** [comment]
With TIDAL, the TV gets a standard Atmos stream (EAC3 JOC), whereas phones get an "immersive stereo" Atmos stream (AC4 IMS), that while technically can potentially be closer to the original master when used with headphones, can ONLY be used with headphones and only with very proprietary players. I'm not sure if this is actually the issue you have since your report is not very detailed (it's unclear if the mobile only option being turned on or off is enabling Atmos downloads), but this may be your issue.

**Comment by NotSimone** [comment]
Yeah its turning `enable_mobile` on that's causing a flac download, while setting it to false is doing the JOC download. I have `prefer_ac4` to false and `spatial_codecs` to false as well, so my understanding is that I should not be getting any JOC downloads, regardless of what `enable_mobile` is set to.

**Comment by OrfiDev** [comment]
Ahhhh I see what you mean, there does seem to be a bug in the code where some fallback code to allow the TV session to get Atmos does not check the spatial codec option, for now using the mobile session should avoid the bug.
